### ISSUE TITLE
Error on my Windows 10 System!

### ISSUE THREAD

**Issue by JohnGrubba** [mafila/psolver#1]
Traceback (most recent call last):
  File "C:\Users\Besitzer\Desktop\psolver\psolve.py", line 958, in <module>
    cm.algo.compile(cm, filecmd=='compile') # compile the model
  File "C:\Users\Besitzer\Desktop\psolver\psolve.py", line 483, in compile
    p1= sp.Popen(['cat']+tgzList, stdout=sp.PIPE)
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Besitzer\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

**Comment by JohnGrubba** [comment]
solve.c: In function 'initPrune':
solve.c:336:11: warning: implicit declaration of function 'fread_unlock'; did you mean '_fread_nolock'? [-Wimplicit-function-declaration]
  336 |     while(fread_unlock(&p,sizeof(uint32_t),1,f) && fread_unlocked(&n,sizeof(uint8_t),1,f) ) {
      |           ^~~~~~~~~~~~
      |           _fread_nolock
solve.c:336:52: warning: implicit declaration of function 'fread_unlocked'; did you mean '_fread_nolock_s'? [-Wimplicit-function-declaration]
  336 |     while(fread_unlock(&p,sizeof(uint32_t),1,f) && fread_unlocked(&n,sizeof(uint8_t),1,f) ) {
      |                                                    ^~~~~~~~~~~~~~
      |                                                    _fread_nolock_s
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x37aa): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x37ea): undefined reference to `fread_unlock'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0xffd1): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0xffed): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x10009): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x10025): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x10199): undefined reference to `fread_unlocked'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Besitzer\AppData\Local\Temp\ccnRgpkM.o:solve.c:(.text+0x101f7): more undefined references to `fread_unlocked' follow
collect2.exe: error: ld returned 1 exit status
Error: solver compilation error 1
[ WARN:0] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-95hbg2jt\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by JohnGrubba** [comment]
Got another Error! Please help me!

**Comment by JohnGrubba** [comment]
When i start the Program it opens the Overview! Then i select a cube via the numbers!
Then it says Compiling and then this pops up!

**Comment by JohnGrubba** [comment]
Ok it's working now! It always used MsysGcc for Compiling! Now i have removed it from the system and it works fine!
